# -*- coding: utf-8 -*-
"""ProgramacaoComputadores1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XwlPrQ9Il2ImezVrlAL-YiVOwnQwCMmf
"""

# Configuração Global

LIMITE_SEGURANCA = 10000.0 # Valor máximo sem suspeita permitida



# Função de análise

def analisar_vendas(v1, v2, v3):

  global LIMITE_SEGURANCA # Permite alterar a variável global



  # Cálculo da média

  media = (v1 + v2 + v3) / 3



  print("=~"*40)

  print("=== RESULTADOS ===")

  print(f"Média das vendas: R$ {media:.2f}")

  print("=~"*40)



  # Verifica se a média ultrapassa o limite de segurança

  if media > LIMITE_SEGURANCA:

    print("!"*40)

    print("SISTEMA EM QUARENTENA")

    print("!"*40)



  # Verifica se a venda ultrapassa o limite

  if v1 > LIMITE_SEGURANCA or v2 > LIMITE_SEGURANCA or v3 > LIMITE_SEGURANCA:



    # Simula decisão do gerente

    resposta = input("Essa venda alta é legítima? (s/n): ")





    if resposta.lower() == 's':

      novo_limite = float(input("Digite o novo limite de segurança: "))

      LIMITE_SEGURANCA = novo_limite

      print(f"Novo LIMITE_SEGURANCA definido: {LIMITE_SEGURANCA}")



  # Verifica discrepância (5x maior que a média)

  if v1 > media * 5 or v2 > media * 5 or v3 > media * 5: # Condição impossivel de chegar. Pelos meus testes funcionou trocando o valor de 5 para 2

   print("=~"*40)

   print("MÉDIA ACIMA DO LIMITE!!! REVISÃO MANUAL NECESSÁRIA")

   print("=~"*40)





  # Exibir tipos das variáveis

  print("\n--- TIPOS DE DADOS ---")

  print(f"v1: {v1} -> {type(v1)}")

  print(f"v2: {v2} -> {type(v2)}")

  print(f"v3: {v3} -> {type(v3)}")

  print(f"media: {media} -> {type(media)}")

  print(f"LIMITE_SEGURANCA: {LIMITE_SEGURANCA} -> {type(LIMITE_SEGURANCA)}")





# Entrada de dados

print("Digite o valor de 3 vendas:")



venda1 = float(input("Venda 1: R$ "))

venda2 = float(input("Venda 2: R$ "))

venda3 = float(input("Venda 3: R$ "))



# Chamada da função

analisar_vendas(venda1, venda2, venda3)

"""# Aula 01

slides no blackboard

# Aula 02
"""

print ("Olá, mundo!")

# A indentação de código se refere aos espaços no inicio de uma linha
if 5 > 2:
  print("Cinco é maior do que dois")
else:
    print("Cinco não é maior que dois")

# Passo 1: Variáveis
num1 = 8
num2 = 12
num3 = 10

# Passo 2: Cálculo
soma = num1 + num2 + num3
media = soma / 3

# Passo 3: Verificar se a média é maior que 10
resultado = "Aprovado" if media >= 10 else "Reprovado"

# Passo 4: Imprimir os resultados
print(":"*40)
print("Número 01", num1)
print("Número 02", num2)
print("Número 03", num3)
print("Soma:", soma)
print("Média:", media)
print("Resultado:", resultado)
print(":"*40)

num1 = int(input("Número 01"))
num2 = int(input("Número 02"))
num3 = int(input("Número 03"))

media = (num1 + num2 + num3) / 3

if media >= 10:
  print ("Aprovado")
else:
  print ("Reprovado")

print("-"*40)
print(f"Número 1: {num1}")
print(f"Número 2: {num2}")
print(f"Número 3: {num3}")
print(f"Média: {media:.2f}")
print("-"*40)

# Cálculo de IMC

# Entrada
peso = float(input("Peso: ").replace(',', '.'))
altura = float(input("Altura: ").replace(',', '.'))

# Processamento
imc= peso / (altura * altura)

# Saída
print ("-"*40)
print(f"Peso: {peso}")
print(f"Alutra: {altura}")
print(f"IMC: {imc:.2f}")
if imc < 18.5:
  print ("Abaixo do peso ideal")
elif imc < 25:
  print ("Peso ideal")
elif imc < 30:
  print ("Sobrepeso")
elif imc < 35:
  print ("Obesidade grau 1")
elif imc < 40:
  print ("Obesidade grau 2")
elif imc >= 40:
  print ("Obesidade grau 3")
else:
  print("Valor inválido")
print ("-"*40)

celsius = float(input("Tempetatura em Celsius"))
fahrenheit =  (celsius * 9/5) + 32
print(f"Temperatura em Fahrenheit: {fahrenheit:.2f}!")

# Teste
x = 10
y = 8.9
z = "Vinicius"
w = True
a = [1,2,3,4,5]
b = [1,2,3,4,5]
c = [1,2,3,4,5]
d = 1j

print ("x:", type(x))
print ("y:", type(y))
print ("z", type(z))
print ("w", type (w))
print ("a", type (a))
print ("b", type (b))
print ("c", type (c))
print ("d", type (d))

# Teste 2

# Valores diferentes
x, y, z, a = "Laranja", "Banana", "Cereja", 12
print(x) # Laranja
print(y) # Banana
print(z) # Cereja
print(a)

a, b, c, d = "Vinicius", 10, True,[1,2,3,4]
print(a)
print(b)
print(c)
print(d)

# Teste 3

# Lista de frutas
frutas = ["maçã", "banana", "cereja"]
x, y, z = frutas
print(x) # maçã
print(y) # banana
print(z) # cereja

# Teste 4

# Dicionário simples
pessoa = {
  "nome": "Ana Silva",
  "idade": 28,
  "profissao": "Engenheira",
  "salario": 5500.00
}

# Acessando valores
print(pessoa["nome"])  # Ana Silva

# Modificando valores
pessoa["idade"] = 29

# Adicionando novas chaves
pessoa["cidade"] = "São Paulo"



"""# Exercicios Py

"""

# Sozinho

# Auditoria de Vendas semanais
LIMITE_SEGURANCA = 10000.0

# Análise
def verificar_limite_seguranca(v1, v2, v3):
    global LIMITE_SEGURANCA

    # Média
    media = (v1 + v2 + v3) / 3
    print(f"Média: R$ {media:.2f}")

    # Analisar
    if media > LIMITE_SEGURANCA:
        print("SISTEMA EM QUARENTENA")

        # decisão do gerente
        resposta = input("Essa transação é legítima? (s/n): ")

        if resposta.lower() == "s":
            novo_limite = float(input("Digite o novo limite: R$ "))
            LIMITE_SEGURANCA = novo_limite
            print(f"Novo limite: R$ {LIMITE_SEGURANCA:.2f}")
    else:
        print("Sistema normal")

# Entrada de dados
venda1 = float(input("Digite o valor da venda 1: R$ "))
venda2 = float(input("Digite o valor da venda 2: R$ "))
venda3 = float(input("Digite o valor da venda 3: R$ "))

# Chamar função
verificar_limite_seguranca(venda1, venda2, venda3)

# JUNTO

# Configuração Global
LIMITE_SEGURANCA = 10000.0 # Valor máximo sem suspeita permitida

# Função de análise
def analisar_vendas(v1, v2, v3):
    global LIMITE_SEGURANCA # Permite alterar a variável global

    # Cálculo da média
    media = (v1 + v2 + v3) / 3

    print("=~"*40)
    print("=== RESULTADOS ===")
    print(f"Média das vendas: R$ {media:.2f}")
    print("=~"*40)

    # Verifica se a média ultrapassa o limite de segurança
    if media > LIMITE_SEGURANCA:
        print("!"*40)
        print("SISTEMA EM QUARENTENA")
        print("!"*40)

    # Verifica se a venda ultrapassa o limite
    if v1 > LIMITE_SEGURANCA or v2 > LIMITE_SEGURANCA or v3 > LIMITE_SEGURANCA:

        # Simula decisão do gerente
        resposta = input("Essa venda alta é legítima? (s/n): ")


        if resposta.lower() == 's':
            novo_limite = float(input("Digite o novo limite de segurança: "))
            LIMITE_SEGURANCA = novo_limite
            print(f"Novo LIMITE_SEGURANCA definido: {LIMITE_SEGURANCA}")

    # Verifica discrepância (5x maior que a média)
    if v1 > media * 5 or v2 > media * 5 or v3 > media * 5: # Condição impossivel de chegar. Pelos meus testes funcionou trocando o valor de 5 para 2
      print("=~"*40)
      print("MÉDIA ACIMA DO LIMITE!!! REVISÃO MANUAL NECESSÁRIA")
      print("=~"*40)


    # Exibir tipos das variáveis
    print("\n--- TIPOS DE DADOS ---")
    print(f"v1: {v1} -> {type(v1)}")
    print(f"v2: {v2} -> {type(v2)}")
    print(f"v3: {v3} -> {type(v3)}")
    print(f"media: {media} -> {type(media)}")
    print(f"LIMITE_SEGURANCA: {LIMITE_SEGURANCA} -> {type(LIMITE_SEGURANCA)}")


# Entrada de dados
print("Digite o valor de 3 vendas:")

venda1 = float(input("Venda 1: R$ "))
venda2 = float(input("Venda 2: R$ "))
venda3 = float(input("Venda 3: R$ "))

# Chamada da função
analisar_vendas(venda1, venda2, venda3)

"""# Aula 03

"""

TAXA_IMPOSTO_EUA = 0.08
TAXA_IMPOSTO_REINO_UNIDO = 0.20
TAXA_IMPOSTO_ALEMANHA = 0.19
TAXA_IMPOSTO_JAPAO = 0.10
TAXA_IMPOSTO_BRASIL = 0.30

def calcular_preco_total(preco_produto, taxa_imposto):
  return preco_produto * (1 + taxa_imposto)

preco_gasolina = 4.50

preco_g_alemanha = calcular_preco_total (preco_gasolina, TAXA_IMPOSTO_ALEMANHA)
preco_g_brasil = calcular_preco_total (preco_gasolina, TAXA_IMPOSTO_BRASIL)
preco_g_eua = calcular_preco_total (preco_gasolina, TAXA_IMPOSTO_EUA)

print(f"Preço da gasolina na Alemanha: $ {preco_g_alemanha:.2f}")
print(f"Preço da gasolina no Brasil: $ {preco_g_brasil:.2f}")
print(f"Preço da gasolina no EUA: $ {preco_g_eua:.2f}")

# Calcular o lucro líquido de uma empresa e verificar se ela atingiu a meta de lucro

receita_total = float(input("Digite a receita total da empresa: "))
custo_fixo = float(input("Digite o custo fixo da empresa: "))
impostos = float(input("Digite os impostos da empresa: "))
despesas_operacionais = float(input("Digite as despesas operacionais da empresa: "))
meta_lucro = float(input("Digite a meta de lucro da empresa: "))

# Cálculos
def calcular_lucro_bruto(receita_total, custo_fixo):
  return receita_total - custo_fixo

# Lucro Operacional é igual a lucro bruto menos despesas operacionais
# Lucro liquiado é igual ao lucro operacional menos os impostos

def calcular_lucro_operacional(receita_total, custo_fixo, despesas_operacionais):
  lucro_bruto = calcular_lucro_bruto(receita_total, custo_fixo)
  return lucro_bruto - despesas_operacionais

def calcular_lucro_liquiado(receita_total, custo_fixo, despesas_operacionais, impostos):
  lucro_operacional = calcular_lucro_operacional(receita_total, custo_fixo, despesas_operacionais)
  return lucro_operacional - impostos

# Realizar os cálculos
lucro_bruto_calculado = calcular_lucro_bruto(receita_total, custo_fixo)
lucro_operacional_calculado = calcular_lucro_operacional(receita_total, custo_fixo, despesas_operacionais)
lucro_liquido_calculado = calcular_lucro_liquiado(receita_total, custo_fixo, despesas_operacionais, impostos)

# Vamos criar um código, para verificar se um funcionário pode ser promovido com base na experiência, desempenho e status de aviso prévio

def verificar_elegibilidade(anos_exp, nota, aviso_prev):
    EXP_MINIMA = 3
    NOTA_MINIMA = 8.0

    # 1º Regra impeditiva
    if aviso_prev:
      return "Você está em aviso prévio. Não é elegível para a promoção."
    # 2º Elegibilidade Total
    if anos_exp >= EXP_MINIMA and nota >= NOTA_MINIMA:
      return "Você é bom para a promoção."
    # 3º Feedback para quem deixou de atingir um dos critérios
    if anos_exp >= EXP_MINIMA:
      return "Seu desempenho ainda não atingiu o nivel mínimo para a promoção"
    if nota >= NOTA_MINIMA:
      return "Você precisa de mais experiência para ser considerado para a promoção"

    return "Você não atende aos critérios minimos para a promoção"

status = verificar_elegibilidade(4,10.0,False)
print (f"Resultado: {status}")

# Fazer os inputs
anos = int(input("Digite a quantidade de anos de experiência: "))
nota = float(input("Nota de desempenho: "))
aviso_previo = input ("Está de aviso prévio (s ou n): ")
if aviso_previo.lower() == 's':
  aviso = True
else:
  aviso = False

status = verificar_elegibilidade(anos,nota,aviso)
print(f"Resultado: {status}")

# ETAPA 1

def processar_vendas():
    total_compra = 0.0
    itens_comprados = 0

    print("Quantos produtos diferentes foram comprados?")
    quantidade_tipos = int(input("Quantidade de tipos: "))

    for i in range(quantidade_tipos):
        nome = input("Nome do produto: ")5

        preco = float(input("Preço unitário: "))
        quantidade = int(input("Quantidade deste produto: "))

        if preco <= 0 or quantidade < 0:
            print("Erro: Valores inválidos para", nome)
        else:
            subtotal = preco * quantidade
            total_compra += subtotal
            itens_comprados += quantidade

    if total_compra > 500:
        total_final = total_compra * 0.90
        print("Desconto de 10% aplicado")
    elif total_compra > 200:
        total_final = total_compra * 0.95
        print("Desconto de 5% aplicado")
    else:
        total_final = total_compra

    print("Resumo:", itens_comprados, "itens. Total a pagar: R$", total_final)


processar_vendas()

#ETAPA 2

def analisar_clima() :
  soma_temperaturas = 0.0
  dias_quentes = 0
  alerta_extremo = False

  for dia in range (1, 8):
    temp = float(input(f"Digite a temperatura do dia {dia}: "))
    soma_temperaturas = soma_temperaturas + temp

    if temp > 35:
      dias_quentes = dias_quentes + 1
      if temp > 45 or temp < -5:
        alerta_extremo = True

  media = soma_temperaturas / 7
  print(f"Média semanal:", media)
  print(f"Dias acima de 35º:", dias_quentes)

  if alerta_extremo == True:
    print ("CUIDADO: Condições perigosas detectadas!")
  else:
      print("Clima dentro da normalidade operacional")

analisar_clima()

5
# ETAPA 3

def sistema_notas_turma():

    total_alunos = int(input("Quantos alunos existem na turma? "))

    for j in range(total_alunos):

        aluno_nome = input("Nome do aluno: ")

        n1 = float(input("Nota 1: "))
        n2 = float(input("Nota 2: "))

        media_aluno = (n1 + n2) / 2

        if media_aluno >= 7.0:
            print(aluno_nome, ": Aprovado com média", media_aluno)

        elif media_aluno >= 5.0:
            print(aluno_nome, ": Recuperação (Média:", media_aluno, ")")

        else:
            print(aluno_nome, ": Reprovado")


sistema_notas_turma()

7
# ETAPA 4

def simulador_poupanca():

    saldo = float(input("Valor inicial do investimento: "))
    taxa = float(input("Taxa de juros mensal (em %): "))
    meses = int(input("Número de meses da simulação: "))

    for m in range(1, meses + 1):

        aporte = float(input("Quanto deseja depositar no mês " + str(m) + "? (0 para nenhum) "))

        saldo = saldo + aporte

        juros = saldo * (taxa / 100)
        saldo = saldo + juros

        print("Mês", m, ": Saldo atualizado = R$", saldo)

        if saldo > 10000.0:
            print("Parabéns! Você atingiu a meta de 10k no mês", m)

    print("Resultado final após", meses, "meses: R$", saldo)


simulador_poupanca()

"""# Testes

"""

input("numero é maior 8 ou 10?")
if 8 > 10:
    print("Numero 8 é maior que 10")
else:
    print("Numero 10 é maior que 8")

"""# EXPERIENCIA 03"""

Função, While, If aninhado e Operadores de Comparação

# Funcionalidade de Login de um banco
# def: Cria um bloco de código reutilizável (função)
def sistema_de_login():
  print("--- Portal Bancário: Acesso Restrito ---")

  # Variáveis de controle
  senha_cadastrada = "Python@2026" # Obs: na "vida real" essa informação é criptografada
  tentativas_falhas = 0
  limite_tentativas = 3
  acesso_liberado = False

  # while: (loop) Executa um bloco de código repetidamente 'enquanto uma condição for verdadeira'.
  # whie -> enquanto
  # and -> E inclusivo
  while tentativas_falhas < limite_tentativas and not acesso_liberado:
      senha_digitada = input(f"Tentativas {tentativas_falhas + 1} / {limite_tentativas} - Digite a senha:")
      if senha_digitada == senha_cadastrada:
          acesso_liberado = True
          print ("Acesso liberado!")
      else:
          # += como um "operador rápido" para incrementar 1
          tentativas_falhas += 1 # tentativas_falhas = tentativas_falhas + 1
          print ("Status: SENHA INCORRETA")
          # IF ANINHADO (Nested IF)
          if len(senha_digitada) > 8:
            # Só verifica o tamanho da senha se ela estiver errada
            print("A senha deve conter no minimo 8 caracteres.")
          if tentativas_falhas == limite_tentativas and senha_digitada != senha_cadastrada:
            print("Limite de tentativas excedido. Acesso bloqueado.")
            break

sistema_de_login()

"""# Exemplo 2"""

função, match-case, for, operadores matematicos

from ast import MatchOr
# Green Tech (Simulação e Crescimento de Emissões)
def prever_pegada_de_carbono():
  print("--- Simulador ambiental de data centers ---")

  # Entrada de Dados
  matriz_energetica = input("Escolha a fonte de energia (solar, eolica, carvão, gas)").lower()

  mese_projecao = int(input("Digite a quantidade de meses para a projeção: "))

  consumo_base_kwh = 1000.0 # Consumo inicial no mês zero

  taxa_crescimento_mensal = 0.05 # O consumo crsce 5% ao mês devido a novos usuários

  match matriz_energetica:
    # O caractere | significa 'ou' da tabela verdade
    case "solar" | "eolica":
      fator_emisao = 0.04
      print("-> Fonte renovavel detectada. ")
    case "gas":
      fator_emisao = 0.40
      print("-> Fator de transição detectada. ")
    case "carvao":
      fator_emisao = 1.20
      print("-> ATENÇÃO: Fonte altamente poluente detectada ")
    case _: # O caso underline é o default, caso os usuários digitem algo diferente
      fator_emisao = 0.50
      print("-> Fonte desconhecida. Usando a média global.")

  emissao_acumulada = 0
  # Estrutura de repetição do FOR
  for mes in range(1, mese_projecao + 1):
    # Matemática: (Juros compostos)
    #Montante = capital * (1 + taxa) ** tempo
    consumo_projetado = consumo_base_kwh * ((1 + taxa_crescimento_mensal) ** mes)

    # Emissão daquele mes especifico
    emissao_mes = consumo_projetado * fator_emisao
    emissao_acumulada += emissao_mes #Operador de incremento

    print(f"Mês {mes}: Consumo = {consumo_projetado:.2f} KWh, Emissao = {emissao_mes:.2f} kg de CO2")

  print(f"\nResumo: em {mese_projecao} meses, o total emitido de {emissao_acumulada:.2f} kg de CO2")

prever_pegada_de_carbono()

"""# Exemplo 3

"""

Loops aninhados (for dentro de for) e if-elif-else (decisão encadeada)

# Carros autônomos enxergam o mundo por meio de "matrizes de pixel "

def processar_visao_computacional():
  print("--- Processador de Imagens de Visão Computacional ---")
  print("--- IA de um carro autônomo ---")
  # Uma imagem é uma matriz
  # Matriz 3 x 3 simulando a foto minúscula da câmera de um carro
  # Valores de 0 (preto) a 255
  imagem_sensor = [
      [10,15,20], # Linha 1: Asfalto escuro
      [30,250,45], # Linha 2: claro, farol de um carro
      [12,18,14], # Linha 3: escuro (alterado 18.14 para 18, 14)
  ]

  alerta_farol = False

  for indice_linha, linha in enumerate(imagem_sensor):
    print(f"Lendo linha {indice_linha + 1}...")

    for pixel in linha:
      if pixel >= 200:
        print(f" -> Pixel detectado: {pixel} (Brilho Intenso - Possível veículo na contramão)")
        alerta_farol = True # flag ativada
      elif pixel >= 100:
        print(f" -> Pixel detectado: {pixel} (Luminosidade Média = Placa reflexiva ou poste)")
      else:
        print (f" -> Pixel detectado: {pixel} (Baixo Brilho - Área escura)")

  if alerta_farol: # Alerta TRUE
    print ("Ativar freios de emergência")
  else:
    print ("Manter velocidade de cruzeiro")

processar_visao_computacional()

#

def analisar_microclima():

    # Lista de listas
    # [local, horario, temperatura, umidade, iqa]

    dados_locais = [
        ["Parque Linear Tiquatira", "08:00", 24, 96, 35],
        ["Parque Linear Tiquatira", "14:00", 29, 90, 42],
        ["Avenida Dom Helder Câmara", "08:00", 27, 60, 80],
        ["Avenida Dom Helder Câmara", "14:00", 33, 45, 115],
        ["Ponto de ônibus Jardim Popular", "08:00", 26, 95, 55],
        ["Ponto de ônibus Jardim Popular", "14:00", 34, 92, 95]
    ]

    print("ANÁLISE DO MICROCLIMA LOCAL")
    print("-" * 50)

    # Primeiro for
    for local in dados_locais:

        nome = local[0]
        horario = local[1]
        temperatura = local[2]
        umidade = local[3]
        iqa = local[4]

        # Classificação do IQA
        if iqa <= 40:
            faixa = 1
        elif iqa <= 80:
            faixa = 2
        elif iqa <= 120:
            faixa = 3
        else:
            faixa = 4

        match faixa:
            case 1:
                qualidade = "Boa"
            case 2:
                qualidade = "Moderada"
            case 3:
                qualidade = "Ruim"
            case 4:
                qualidade = "Muito Ruim"

        # Nota de conforto urbano
        nota = 10

        if temperatura > 30 or temperatura < 20:
            nota -= 2

        if umidade < 40:
            nota -= 2

        if iqa > 80:
            nota -= 3

        if nota < 0:
            nota = 0

        print("\nLocal:", nome)
        print("Horário:", horario)
        print("Temperatura:", temperatura, "°C")
        print("Umidade:", umidade, "%")
        print("IQA:", iqa)
        print("Qualidade do Ar:", qualidade)
        print("Nota de Conforto Urbano:", nota)

        # Segundo for (for aninhado)
        print("Valores registrados:")
        for valor in local:
            print(valor)


analisar_microclima()

"""# exercicios ia 01


"""

# Primeira atividade em casa

nome = input ("qual seu nome?")
print (f"Olá, {nome}")

# Segunda atividade em casa

numero = int(input("Digite um número: "))

resultado = numero * 2

print("Resultado:", resultado)

"""# Experiência 04"""

Estrutura de Repetição - Contada

# Comando que lista os numeros do 0 ate o numero desejada.

for i in range(5): # 0 e vai até 4
  print(i)

# Comando para Listar números
numeros = [1,2,3,4,5]

for numero in numeros:
  print(numero)

# Dicionário
frutas = {"maça": 1, "banana": 2, "laranja": 3}

for fruta in frutas:
  print(fruta + ":" + str(frutas[fruta]))

# Tupla de cores

cores = ("vermelho", "verde", "azul")

for cor in cores:
  print(cor)

"""Lista: é uma estrutura de dados ordenada e mutável"""

lista = [1,2,3,4,5]

print("Antes:", lista)
# Adcionar um elemento no final da lista
lista.append(6)

print("Depois:", lista)

# Remover o último elemento da lista
lista.pop()

print("Removendo:", lista)

# Ordenando a lista
lista.sort()

print ("Lista ordenada:", lista)

"""Tupla: é uma estrutura de dado ordenada e imutável"""

tupla = (1,3,3,3,3)

indice = tupla.index(1)

print("Pos 1:", indice)

contagem = tupla.count(3)

print("Num 3:", contagem)

"""**Dicionário:** é uma estrutura de dados que mapeia chaves únicas para valores associados"""

del print

dicionario ={
    "nome": "João",
    "idade": 30,
    "cidade": "São Paulo"
}

nome = dicionario["nome"]

print("Nome:", nome)

idade = dicionario["idade"]

print("Idade:", idade)

dicionario["email"] = "j@joao.com"

print("Email:", dicionario["email"])

print(dicionario)

"""**ENTRADA **-> **PROCESSAMENTO** -> **SAÍDA **

-Variáveis (numeros, caracteres, verdade/falso)

---


-Operadores lógicos

---


-Operadores de Comparação

---


-Operadores Matemáticos

---


-Condicionais

---


-Loop

---


-Métodos/Funções

**Guia de Estudo:** https://www.w3schools.com/

# Exemplo 01
"""

tamanho = 8

# Loop para gerar linhas
for linha in range(tamanho):
  # Loop para gerar as colunas
  for coluna in range (tamanho):
    # Se a soma dos indices da linha e da coluna for par, a casa é preta
    if(linha + coluna) % 2 == 0:
      print ("0", end=" ")
    else:
      print("1", end=" ")
  print()

matriz_01 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

matriz_02 = [
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
]

resultado = [
    [0,0,0],
    [0,0,0],
    [0,0,0]
]

# Loop para as linhas
for i in range(len(matriz_01)):
  # Loop para as colunas
  for j in range(len(matriz_02[0])):
    # Loop para multiplicação e soma dos elementos
    for k in range(len(matriz_02)):
      resultado[i][j] += matriz_01[i][j] * matriz_02[k][j]

  # Imprimindo o resultado
  for linha in resultado:
    print(linha)

"""# Exercicio 02"""

import matplotlib.pyplot as plt

# Desafio 1: O Criador de Emojis (Pixels RGB)
emoji_data = {
    "nome": "Smile",
    "grade": [
        [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)], # Linha 0
        [(255,255,0), (0,0,0),     (255,255,0), (0,0,0),     (255,255,0)], # Linha 1 (Olhos)
        [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)], # Linha 2
        [(255,255,0), (0,0,0),     (0,0,0),     (0,0,0),     (255,255,0)], # Linha 3 (Boca)
        [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)]  # Linha 4
    ]
}

nova_grade = []

# Nível 1: Percorrendo o Dicionário (Lote)
for chave, valor in emoji_data.items():
    if chave == "grade":
        # Nível 2: Percorrendo as Linhas
        for linha in valor:
            nova_linha = []
            # Nível 3: Percorrendo os Pixels
            for pixel in linha:
                # Lógica do Filtro: Se for Amarelo (255, 255, 0)
                if pixel == (255, 255, 0):
                    # Criando nova tupla com brilho reduzido (50%)
                    pixel_sombreado = (pixel[0] // 2, pixel[1] // 2, pixel[2] // 2)
                    nova_linha.append(pixel_sombreado)
                else:
                    # Se for preto (ou outra cor), mantém original
                    nova_linha.append(pixel)

            nova_grade.append(nova_linha)

# Atualizando o dicionário original com a nova grade
emoji_data["grade"] = nova_grade

# Print para conferir o resultado
print(f"Emoji: {emoji_data['nome']}")
for linha in emoji_data["grade"]:
    print(linha)

plt.imshow(emoji_data["grade"])
plt.show()

biblioteca_musical = {
    "Toques": [
        {"Alegre": ([440, 480], [520, 560])},
        {"Triste": ([200, 150], [100, 50])}
    ]
}

for chave, lista in biblioteca_musical.items():   # 1º nível

    for musica in lista:                          # 2º nível

        for nome, matriz in musica.items():       # 3º nível

            print("\nMúsica:", nome)
            print("Original:")

            for linha in matriz:
                print(linha)

            # transposição
            nova_matriz = []

            for i in range(len(matriz[0])):
                nova_linha = []

                for j in range(len(matriz)):
                    nova_linha.append(matriz[j][i])

                nova_matriz.append(nova_linha)

            musica.update({nome: nova_matriz})

            print("Transposta:")

            for linha in nova_matriz:
                print(linha)

playlist_imagens = {
    "Playlist": [
        {"Smile": [(255,255,0), (0,0,0), (255,255,0)]},
        {"Noite": [(0,0,0), (50,50,100), (0,0,0)]}
    ]
}

for chave in playlist_imagens.keys():            # 1º nível

    for imagem in playlist_imagens[chave]:       # 2º nível

        for nome, pixels in imagem.items():      # 3º nível

            nova_lista = []

            for pixel in pixels:

                r,g,b = pixel

                novo_pixel = (r//2, g//2, b//2)

                nova_lista.insert(len(nova_lista), novo_pixel)

            imagem[nome] = nova_lista


# removendo última imagem da playlist
playlist_imagens["Playlist"].pop()

print("\nPlaylist final:")

for imagem in playlist_imagens["Playlist"]:
    print(imagem)

from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI()

# lista que guarda as tarefas
tarefas = []

# modelo da tarefa
class Tarefa(BaseModel):
    titulo: str
    descricao: str
    concluida: bool = False


# rota inicial
@app.get("/")
def inicio():
    return {"mensagem": "API Organizador de Rotina"}


# listar tarefas
@app.get("/tarefas")
def listar_tarefas():
    return tarefas


# criar tarefa
@app.post("/tarefas")
def criar_tarefa(tarefa: Tarefa):
    tarefas.append(tarefa)
    return {"mensagem": "Tarefa criada com sucesso"}


# marcar tarefa como concluída
@app.put("/tarefas/{id}")
def concluir_tarefa(id: int):
    tarefas[id].concluida = True
    return {"mensagem": "Tarefa concluída"}


# deletar tarefa
@app.delete("/tarefas/{id}")
def deletar_tarefa(id: int):
    tarefas.pop(id)
    return {"mensagem": "Tarefa removida"}