# -*- coding: utf-8 -*-
"""traduzindo-logica-para-python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mNfapfY2liTWQ2eqq1rW7w--QCyjHfcb
"""

# ETAPA 1

def processar_vendas():

  total_compra = 0.0

  itens_comprados = 0



  print("Quantos produtos diferentes foram comprados?")

  quantidade_tipos = int(input("Quantidade de tipos: "))



  for i in range(quantidade_tipos):

    nome = input("Nome do produto: ")5



    preco = float(input("Preço unitário: "))

    quantidade = int(input("Quantidade deste produto: "))



    if preco <= 0 or quantidade < 0:

      print("Erro: Valores inválidos para", nome)

    else:

      subtotal = preco * quantidade

      total_compra += subtotal

      itens_comprados += quantidade



  if total_compra > 500:

    total_final = total_compra * 0.90

    print("Desconto de 10% aplicado")

  elif total_compra > 200:

    total_final = total_compra * 0.95

    print("Desconto de 5% aplicado")

  else:

    total_final = total_compra



  print("Resumo:", itens_comprados, "itens. Total a pagar: R$", total_final)





processar_vendas()



#ETAPA 2



def analisar_clima() :

 soma_temperaturas = 0.0

 dias_quentes = 0

 alerta_extremo = False



 for dia in range (1, 8):

  temp = float(input(f"Digite a temperatura do dia {dia}: "))

  soma_temperaturas = soma_temperaturas + temp



  if temp > 35:

   dias_quentes = dias_quentes + 1

   if temp > 45 or temp < -5:

    alerta_extremo = True



 media = soma_temperaturas / 7

 print(f"Média semanal:", media)

 print(f"Dias acima de 35º:", dias_quentes)



 if alerta_extremo == True:

  print ("CUIDADO: Condições perigosas detectadas!")

 else:

   print("Clima dentro da normalidade operacional")



analisar_clima()





# ETAPA 3



def sistema_notas_turma():



  total_alunos = int(input("Quantos alunos existem na turma? "))



  for j in range(total_alunos):



    aluno_nome = input("Nome do aluno: ")



    n1 = float(input("Nota 1: "))

    n2 = float(input("Nota 2: "))



    media_aluno = (n1 + n2) / 2



    if media_aluno >= 7.0:

      print(aluno_nome, ": Aprovado com média", media_aluno)



    elif media_aluno >= 5.0:

      print(aluno_nome, ": Recuperação (Média:", media_aluno, ")")



    else:

      print(aluno_nome, ": Reprovado")





sistema_notas_turma()





# ETAPA 4



def simulador_poupanca():



  saldo = float(input("Valor inicial do investimento: "))

  taxa = float(input("Taxa de juros mensal (em %): "))

  meses = int(input("Número de meses da simulação: "))



  for m in range(1, meses + 1):



    aporte = float(input("Quanto deseja depositar no mês " + str(m) + "? (0 para nenhum) "))



    saldo = saldo + aporte



    juros = saldo * (taxa / 100)

    saldo = saldo + juros



    print("Mês", m, ": Saldo atualizado = R$", saldo)



    if saldo > 10000.0:

      print("Parabéns! Você atingiu a meta de 10k no mês", m)



  print("Resultado final após", meses, "meses: R$", saldo)





simulador_poupanca()