# -*- coding: utf-8 -*-
"""desenho-emojis-com-dados

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ydj2CuN1AIXZa4FEw6aPsz5TogtFZ9e2
"""

import matplotlib.pyplot as plt



# Desafio 1: O Criador de Emojis (Pixels RGB)

emoji_data = {

  "nome": "Smile",

  "grade": [

    [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)], # Linha 0

    [(255,255,0), (0,0,0),  (255,255,0), (0,0,0),  (255,255,0)], # Linha 1 (Olhos)

    [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)], # Linha 2

    [(255,255,0), (0,0,0),  (0,0,0),  (0,0,0),  (255,255,0)], # Linha 3 (Boca)

    [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)] # Linha 4

  ]

}



nova_grade = []



# Nível 1: Percorrendo o Dicionário (Lote)

for chave, valor in emoji_data.items():

  if chave == "grade":

    # Nível 2: Percorrendo as Linhas

    for linha in valor:

      nova_linha = []

      # Nível 3: Percorrendo os Pixels

      for pixel in linha:

        # Lógica do Filtro: Se for Amarelo (255, 255, 0)

        if pixel == (255, 255, 0):

          # Criando nova tupla com brilho reduzido (50%)

          pixel_sombreado = (pixel[0] // 2, pixel[1] // 2, pixel[2] // 2)

          nova_linha.append(pixel_sombreado)

        else:

          # Se for preto (ou outra cor), mantém original

          nova_linha.append(pixel)



      nova_grade.append(nova_linha)



# Atualizando o dicionário original com a nova grade

emoji_data["grade"] = nova_grade



# Print para conferir o resultado

print(f"Emoji: {emoji_data['nome']}")

for linha in emoji_data["grade"]:

  print(linha)



plt.imshow(emoji_data["grade"])

plt.show()

biblioteca_musical = {

  "Toques": [

    {"Alegre": ([440, 480], [520, 560])},

    {"Triste": ([200, 150], [100, 50])}

  ]

}



for chave, lista in biblioteca_musical.items(): # 1º nível



  for musica in lista:             # 2º nível



    for nome, matriz in musica.items():   # 3º nível



      print("\nMúsica:", nome)

      print("Original:")



      for linha in matriz:

        print(linha)



      # transposição

      nova_matriz = []



      for i in range(len(matriz[0])):

        nova_linha = []



        for j in range(len(matriz)):

          nova_linha.append(matriz[j][i])



        nova_matriz.append(nova_linha)



      musica.update({nome: nova_matriz})



      print("Transposta:")



      for linha in nova_matriz:

        print(linha)

playlist_imagens = {

  "Playlist": [

    {"Smile": [(255,255,0), (0,0,0), (255,255,0)]},

    {"Noite": [(0,0,0), (50,50,100), (0,0,0)]}

  ]

}



for chave in playlist_imagens.keys():      # 1º nível



  for imagem in playlist_imagens[chave]:   # 2º nível



    for nome, pixels in imagem.items():   # 3º nível



      nova_lista = []



      for pixel in pixels:



        r,g,b = pixel



        novo_pixel = (r//2, g//2, b//2)



        nova_lista.insert(len(nova_lista), novo_pixel)



      imagem[nome] = nova_lista





# removendo última imagem da playlist

playlist_imagens["Playlist"].pop()



print("\nPlaylist final:")



for imagem in playlist_imagens["Playlist"]:

  print(imagem)