# -*- coding: utf-8 -*-
"""engenharia-de-contexto-e-logistica-fisica

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m5lpYiEXs_fXiEx-qQuAi8_GLGSYYpcy
"""

1.

# Algoritmo do microclima local (Pesquisa + Código 1)



def analisar_microclima():



  # Lista de listas

  # [local, horario, temperatura, umidade, iqa]



  dados_locais = [

    ["Parque Linear Tiquatira", "08:00", 24, 96, 35],

    ["Parque Linear Tiquatira", "14:00", 29, 90, 42],

    ["Avenida Dom Helder Câmara", "08:00", 27, 60, 80],

    ["Avenida Dom Helder Câmara", "14:00", 33, 45, 115],

    ["Ponto de ônibus Jardim Popular", "08:00", 26, 95, 55],

    ["Ponto de ônibus Jardim Popular", "14:00", 34, 92, 95]

  ]



  print("ANÁLISE DO MICROCLIMA LOCAL")

  print("-" * 50)



  # Primeiro for

  for local in dados_locais:



    nome = local[0]

    horario = local[1]

    temperatura = local[2]

    umidade = local[3]

    iqa = local[4]



    # Classificação do IQA

    if iqa <= 40:

      faixa = 1

    elif iqa <= 80:

      faixa = 2

    elif iqa <= 120:

      faixa = 3

    else:

      faixa = 4



    match faixa:

      case 1:

        qualidade = "Boa"

      case 2:

        qualidade = "Moderada"

      case 3:

        qualidade = "Ruim"

      case 4:

        qualidade = "Muito Ruim"



    # Nota de conforto urbano

    nota = 10



    if temperatura > 30 or temperatura < 20:

      nota -= 2



    if umidade < 40:

      nota -= 2



    if iqa > 80:

      nota -= 3



    if nota < 0:

      nota = 0



    print("\nLocal:", nome)

    print("Horário:", horario)

    print("Temperatura:", temperatura, "°C")

    print("Umidade:", umidade, "%")

    print("IQA:", iqa)

    print("Qualidade do Ar:", qualidade)

    print("Nota de Conforto Urbano:", nota)



    # Segundo for (for aninhado)

    print("Valores registrados:")

    for valor in local:

      print(valor)





analisar_microclima()



2.

#Navegação e Evacuação Espacial (Avaliação + Código 2)



def simular_evacucao():



  # Lista com os locais do trajeto

  locais = ["Quarto", "Corredor", "Sala", "Porta de Entrada", "Rua"]



  # Lista com o estado de cada local

  estados = ["caminho livre", "fumaça", "chave", "porta trancada", "seguro"]



  # Posição inicial do agente

  posicao = 0



  # Energia do agente

  energia = 8



  # Inventário

  tem_chave = False



  print("SIMULADOR DE EVACUAÇÃO")

  print("-" * 40)



  # Loop principal

  while energia > 0:



    local_atual = locais[posicao]

    estado_atual = estados[posicao]



    print("\nAgente está em:", local_atual)

    print("Estado do local:", estado_atual)

    print("Energia restante:", energia)



    # Se chegou ao destino final

    if local_atual == "Rua":

      print("\nO agente chegou à rua com segurança!")

      break



    # Verifica o estado do local

    if estado_atual == "caminho livre":

      print("O caminho está livre. O agente avança.")

      posicao += 1



    elif estado_atual == "fumaça":

      print("Há fumaça no local, mas o agente consegue passar com cuidado.")

      posicao += 1

      energia -= 1



    elif estado_atual == "chave":

      print("O agente encontrou uma chave.")

      tem_chave = True

      posicao += 1



    elif estado_atual == "porta trancada":

      print("A saída está trancada.")



      # If aninhado

      if tem_chave == True:

        print("O agente tem a chave e conseguiu abrir a porta.")

        posicao += 1

      else:

        print("O agente não tem a chave, então precisa voltar.")

        posicao -= 1

        energia -= 1



    elif estado_atual == "seguro":

      print("Local seguro.")

      posicao += 1



    # Garante que o agente não saia dos limites da lista

    if posicao < 0:

      posicao = 0



    if posicao >= len(locais):

      posicao = len(locais) - 1



    # Gasto básico de energia a cada tentativa

    energia -= 1


  # Caso a energia acabe

  if energia <= 0 and locais[posicao] != "Rua":

    print("\nO agente ficou sem energia antes de chegar à saída.")



simular_evacucao()

"""3.

Durante a elaboração da Parte 2, percebi que programar não significa apenas escrever códigos, mas aprender a organizar a realidade de forma lógica. Para criar o mapa de evacuação, precisei observar um ambiente comum, a minha casa, e transformá-lo em etapas claras, separando locais, obstáculos e possíveis caminhos. Algo que normalmente parece simples no dia a dia precisou ser dividido em pequenas partes para que o computador pudesse entender. Isso mostrou que muitos problemas complexos podem ser resolvidos quando são quebrados em partes menores e analisados com calma.



Aprender a programar também muda a forma como passamos a tomar decisões fora do computador. As estruturas condicionais, como if/else, ensinam a pensar em possibilidades e consequências antes de agir. Na vida cotidiana, isso pode ser aplicado em situações como organizar horários, administrar dinheiro ou escolher a melhor solução para um problema inesperado. Em vez de agir por impulso, começamos a pensar de forma mais estratégica, avaliando cenários e criando alternativas, como se estivéssemos montando um algoritmo mental para resolver a situação.



Além disso, os loops representam a importância da persistência e da melhoria contínua. Muitas vezes, um problema não é resolvido na primeira tentativa, e precisamos repetir processos, corrigir erros e testar novos caminhos até alcançar o resultado desejado. Isso vale tanto na programação quanto na vida pessoal e profissional. Portanto, aprender programação transforma não apenas a capacidade técnica, mas também a maneira de pensar, tornando a pessoa mais analítica, organizada e preparada para enfrentar desafios complexos no cotidiano.
"""